# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 23:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('dataEHoraDeInicio', models.DateField(blank=True, null=True)),
                ('dataEHoraFim', models.DateField(blank=True, null=True)),
                ('cidade', models.CharField(max_length=150, null=True)),
                ('uf', models.CharField(max_length=150, null=True)),
                ('endereco', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validacao', models.BooleanField(verbose_name='Validação')),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventosapp.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('idade', models.IntegerField(max_length=3)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=450)),
                ('valor', models.IntegerField(max_length=30)),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventosapp.Evento')),
            ],
        ),
        migrations.AddField(
            model_name='inscricao',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventosapp.Pessoa'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventosapp.Ticket'),
        ),
    ]
